
export const GET_CATE_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_CATE_PRODUCTS_SUCCESS = 'GET_CATE_PRODUCTS_SUCCESS';
export const GET_CATE_PRODUCTS_FAILURE = 'GET_CATE_PRODUCTS_FAILURE';
// Định nghĩa các loại action ở đây
export const GET_SEARCH_PRODUCTS_SUCCESS = 'GET_SEARCH_PRODUCTS_SUCCESS';
